---
abstract: 'a Perl framework for XML stylesheets'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
  - 'Dominique Quatravaux <domq@cpan.org> '
  - 'Matt Sergeant <matt@sergeant.org>'
build_requires:
  File::Find: '0'
  File::Spec: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-XPathScript
provides:
  XML::XPathScript:
    file: lib/XML/XPathScript.pm
    version: '1.55'
  XML::XPathScript::Processor:
    file: lib/XML/XPathScript/Processor.pm
    version: '1.55'
  XML::XPathScript::Processor::B:
    file: lib/XML/XPathScript/Processor/B.pm
    version: '1.55'
  XML::XPathScript::Processor::LibXML:
    file: lib/XML/XPathScript/Processor/LibXML.pm
    version: '1.55'
  XML::XPathScript::Processor::XPath:
    file: lib/XML/XPathScript/Processor/XPath.pm
    version: '1.55'
  XML::XPathScript::Stylesheet::DocBook2LaTeX:
    file: lib/XML/XPathScript/Stylesheet/DocBook2LaTeX.pm
    version: '1.55'
  XML::XPathScript::Template:
    file: lib/XML/XPathScript/Template.pm
    version: '1.55'
  XML::XPathScript::Template::Content:
    file: lib/XML/XPathScript/Processor.pm
  XML::XPathScript::Template::Tag:
    file: lib/XML/XPathScript/Template/Tag.pm
    version: '1.55'
requires:
  Carp: '0'
  Clone: '0'
  Data::Dumper: '0'
  File::Basename: '0'
  IO::File: '0'
  Readonly: '0'
  Scalar::Util: '0'
  Symbol: '0'
  XML::LibXML: '0'
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: '1.54'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
